### ISSUE TITLE
Trim new lines from ProgramName

### ISSUE THREAD

**Issue by Gubriels** [Gubriels/internal-services-directory#114]

**Comment by Gubriels** [comment]
A lot of the program names had a new line at the end of their strings. cc @fireking220. I think we may want to trim them in the parser.

**Comment by fireking220** [comment]
I don't see any newlines being added in the parser code, and echoing back the programName reveals no newlines anywhere? Can someone else confirm?

**Comment by BHolbs** [comment]
@fireking220 When you run the API endpoints, the program name seems to pretty consistently have the closing quotation on the next line in the outputted JSON. We figured there's no other place where a newline could get inserted, but maybe more digging is in order
