### ISSUE TITLE
Complete remaining schema work

### ISSUE THREAD

**Issue by Gubriels** [Gubriels/internal-services-directory#130]
* programOfferNumber should be unique
* Ids on associations should be joint unique values 
    Ex: Do not allow any serviceCommunityAssociations to have the same serviceID and CommunityID combo.
* Language Name should not be nullable
* Division Code should not be nullable
* Community Name should not be nullable

**Comment by Gubriels** [comment]
Code to fix associations
```
CREATE TABLE [dbo].[ServiceCommunityAssociation](
	--[serviceCommunityAssociationID] [int] IDENTITY(1,1) NOT NULL,
	[serviceID] [int] NOT NULL,
	[communityID] [int] NOT NULL,
 CONSTRAINT [PK__ServiceC__3576AE4967FB1C02] PRIMARY KEY CLUSTERED
(
	[serviceID],[communityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
```

**Comment by BHolbs** [comment]
Division code was not nullable already, just commenting as I work
