### ISSUE TITLE
Spike: Automate developer database setup

### ISSUE THREAD

**Issue by Gubriels** [Gubriels/internal-services-directory#40]
Write a script to automate setting up the database so you can hit it locally with api calls. It should destroy any setup currently there.

**Comment by BHolbs** [comment]
@fireking220 I think looking into "SQL Server Database Project" or "SQL Server Change Automation Project" to figure out how to automate a DB setup so that a user doesn't have to wind up SSMS or manually run a script

**Comment by fireking220** [comment]
I looked at both of those links but couldn't find a solution that gelled with our current API :<
